albumentation:
  blur:
    strength: 3
    prob: 0
  clahe:
    clip_limit: [1, 4]
    tile_grid_size: [8, 8]
    prob: 0
  color_jitter:
    brightness: [1, 1]
    contrast: [1, 1]
    saturation: [1, 1]
    hue: [0, 0]
    prob: 1
  coarse_dropout:
    max_holes: 1
    max_height: 50
    max_width: 50
    min_holes: 1
    min_height: 50
    min_width: 50
    fill_value: [255, 255, 255]
    prob: 1
  downscale:
    scale_min: 0.5
    scale_max: 2
    prob: 0
